apiVersion: apps/v1 #Versão da API 
kind: Deployment #Especifica o que esta sendo criado
metadata: #Contem info sobre o deployment
  name: nginx-busybox-deployment
spec: #Especificação do deployment
  replicas: 1
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec: #Especificação do pod
      containers: #Lista de containers no pod
      - name: first-container
        image: nginx:latest #Executa a imagem do nginx
        ports: 
        - containerPort: 80
      - name: second-container
        image: busybox #Executa a imagem e imprime uma imagem
        command: ["sh", "-c", "while true; do echo 'Hello from BusyBox'; sleep 3600; done"]
