apiVersion: apps/v1 #Versão da API 
kind: Deployment #Especifica o que esta sendo criado
metadata: #Contem info sobre o deployment
  name: nginx-busybox-deployment
spec: #Especificação do deployment
  replicas: 1 #Numero de Replicas do pod
  selector:
    matchLabels:
      app: multi-container-app
  template:
    metadata:
      labels:
        app: multi-container-app
    spec: #Especificação do pod
      containers: #Lista de containers no pod
      - name: first-container
        image: nginx:latest #Executa a imagem do nginx
        ports: 
        - containerPort: 80
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html #Caminho dentro do container onde o volume será criado
      - name: second-container
        image: busybox #Executa a imagem e imprime uma imagem
        command: ["/bin/sh", "-c"]
        args:
        - |
          while true; do
            echo "<html><body><h1>Lily&Luna</h1></body></html>" > /usr/share/nginx/html/index.html;
            sleep 1;
          done
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html-volume
        emptyDir: {} #Volume temporário
        
      
